# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "local/ckit"

env:
  VIRTUAL_ENV: "/abc/$PATH"
  PATH: "/some/path:$PATH"

command:
  test:
    - "echo 'ok'"