## From: github.com/nfra-project/nfra-skel
##
## Build

name: release_build_and_push_to_github

## SECURITY: Do not youe "pull_request_target" nr "pull_request" here! See
## https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  push:
    branches:
      - release-[0-9.]+

jobs:
  build_and_push_github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: "CI_BUILD_NAME=${GITHUB_REF#refs/heads/release-} && CI_REGISTRY_IMAGE=$CI_REGISTY/$GITHUB_REPOSITORY && env && ./.kicker/kickstart.static.sh -ci_build"
        with:
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_USER: giblab-user
          CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}



